language: python
python:
  - 3.6.10
env:
  - BUILD_TYPE="Release"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran liblapack-dev
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print(numpy.__version__)"
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update
  - rm -rf amrclaw
  - ln -s ../ amrclaw
  
install:
  - export PYTHONPATH=${PWD}:$PYTHONPATH
  - export CLAW=${PWD}
  - export FC=gfortran
  - cd amrclaw
  
before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
  - echo "PYTHONPATH="$PYTHONPATH
  - echo "CLAW="$CLAW
  - echo "FC="$FC
  
script:
  - cd $CLAW/amrclaw
  - nosetests -sv

after_failure:
 - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done
  
notifications:
  email: false
